### ISSUE TITLE
Descriptif de session: lien auteur, ...

### ISSUE THREAD

**Issue by etievent** [caradojo/caradojo.github.io#32]
- Ca pourrait être utile de rajouter "http://" en début du lien si ce n'est pas mis (sinon c'est un chemin relatif).
- Il y a aussi un ":" avant la biographie.

**Comment by martinsson** [comment]
A propos du manque de http:// en début de lien, je n'arrive pas à comprendre. Par exemple il manquerait quoi sur cette session? http://2015.agile-grenoble.org/programme.html#/session/625. Sinon as-tu un autre exemple?

**Comment by etievent** [comment]
Un exemple ici:
http://2015.agile-grenoble.org/programme.html#/session/614
le lien donne;
http://2015.agile-grenoble.org/www.fcube-lab.com

Sur l'exemple que tu donnes ( http://cfp.agile-grenoble.org/presenters/137/edit ), le "http://" est bien entré dans le champ website, contrairement à l'exemple ci-dessus.

Pour le thème, sur l'exemple que tu donnes, on a:
"Thème: tech"
au lieu de
"Thème: Nouveaux savoir-faire & competences"
